<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>    
  <xsl:template match="/">      
    <xsl:text>
# SSHD Configuration File
#
# Automatically-generated by sysrepo
#
</xsl:text>
    <xsl:for-each select="//*[not(*)]">        
      <xsl:choose>
	<xsl:when test="text()">
	  <xsl:value-of select="local-name()"/> <xsl:value-of select="concat(' ',., '&#10;')"/>      
	</xsl:when>
	<xsl:otherwise>
	  <xsl:value-of select="concat('# ',local-name())"/> <xsl:value-of select="concat(' ',., '&#10;')"/>
	</xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>    
  </xsl:template>    
</xsl:stylesheet>
