/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: if.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IF_H_
#define _IF_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef if__ns
#define if__ns 201468376
#define if__ns_id "http://tail-f.com/ns/example/if"
#define if__ns_uri "http://tail-f.com/ns/example/if"
#endif

#define if_name 1998270519
#define if_dropped 1815365056
#define if_interface 221572658
#define if_transmit 1705430781
#define if_receive 716682309
#define if_bytes 1113108825
#define if_collisions 71575584
#define if_prefix_length 524393771
#define if_errors 1226221644
#define if_status 1950810920
#define if_address 1266954393
#define if_packets 384560432
#define if_interfaces 321503962

#ifdef __cplusplus
}
#endif

#endif
